name: TAF DP
favicon: null
layout_spectrum: 0.22931
typography_spectrum: 0.36441
title: '-DESIGN PORTFOLIO-'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00be00'
    - '#486138'
    - '#6a8e7f'
    - '#fefefe'
    - '#bdd0d4'
  brandStrength: 0.9484843278769404
  lightness: 0.06851464067585766
  saturation: 0.5316349677741528
  rhythmicContrast: 0.3342463690787554
purpose: []
